### ISSUE TITLE
How to run the code

### ISSUE THREAD

**Issue by shabesoglu** [soegaard/remacs#3]
Hi,

I am still learning Racket, and the project is interesting, but I do not know how to run it. Could you provide info how to run?

**Comment by soegaard** [comment]
Hi,

Clone the repository.
Open "editor.rkt" in DrRacket.
Click the run button.


But ... I can't remember what state I left the code in.
Don't expect too much.

/Jens Axel

**Comment by shabesoglu** [comment]
Thanks, it works just fine :)
